# 
# Timer
# 
timer:
  snooze_door_left_open_automation:
    name: Snooze Door Left Open Automation
    duration: "00:30:00"
    restore: true
    icon: mdi:rewind-30

# 
# Automations
# 
automation:
  - id: "door_left_open"
    alias: "Door Left Open"
    mode: "single"
    initial_state: on
    triggers:
      - trigger: state
        entity_id:
          - binary_sensor.interior_garage_door
          - binary_sensor.front_door_status
        to: "on"
        for:
          minutes: 5
      - trigger: state
        entity_id:
          - binary_sensor.interior_garage_door
          - binary_sensor.front_door_status
        to: "on"
        for:
          minutes: 10
      - trigger: state
        entity_id:
          - binary_sensor.interior_garage_door
          - binary_sensor.front_door_status
        to: "on"
        for:
          minutes: 15
      # Trigger when the timer is finished
      - trigger: event
        event_type: timer.finished
        event_data: 
          entity_id: timer.snooze_door_left_open_automation
    conditions:
      # Only run if the timer is idle
      - condition: state
        entity_id: timer.snooze_door_left_open_automation
        state: "idle"
      # Only run if the door is open
      - condition: or
        conditions:
          - condition: state
            entity_id: binary_sensor.interior_garage_door
            state: "on"
          - condition: state
            entity_id: binary_sensor.front_door_status
            state: "on"
    actions:
    # 
      # Set the action variables
      # 
      - variables:
          action_snooze: "{{ 'SNOOZE_' ~ context.id }}"

      # Call the announcement engine
      # Announcement
      - action: script.voice_announcement
        data:
          media_players: auto
          sound: "police-whistle"
          priority: high
          speech_message: "{{ trigger.from_state.attributes.friendly_name }} has been open for too long, please close the door!"

      #
      # Send a notification and let us snooze the automation
      # 
      - action: script.general_notification
        data:
          title: Exterior House Doors
          message: "{{ trigger.from_state.attributes.friendly_name }} has been open for too long, please close the door!"
          devices: "all"
          priority: "time-sensitive"
          tag: "door-open"
          actions:
            - action: "{{ action_snooze }}"
              title: "Snooze 30 Minutes"

      # 
      # Wait for us to respond to the actionable notification to 
      # snooze the automation
      #
      - wait_for_trigger:
          - trigger: event
            event_type: mobile_app_notification_action
            event_data:
              action: "{{ action_snooze }}"
        timeout:
          minutes: 3

      - if:
          - condition: template
            value_template: "{{ wait.trigger.event.data.action == action_snooze }}"
        then:
          - action: timer.start
            entity_id: timer.snooze_door_left_open_automation


        
