# Backyard South Camera Detects an Animal
#
automation:
  - id: "backyard_south_camera_detections_animal"
    alias: "Backyard South Camera Detections - Animal"
    mode: "single"
    triggers:
      - trigger: state
        entity_id: binary_sensor.backyard_south_camera_animal_detected
        to: "on"
        variables:
          camera_name: "Backyard South Camera"
          nvr_id: "{{ config_entry_id(trigger.entity_id) }}"
          event_id: "{{ trigger.to_state.attributes.event_id }}"
          image_path: /api/unifiprotect/thumbnail/{{ nvr_id }}/{{ event_id }}
          proxy_camera: camera.camera_proxy_camera_backyard_south_camera_high
          snooze_timer: timer.backyard_south_camera_notifications_snooze_timer
          notifications_boolean: input_boolean.backyard_south_camera_notifications
    conditions:
      - condition: template
        value_template: "{{ ( now().timestamp() - as_timestamp(state_attr('automation.backyard_south_camera_detections_animal','last_triggered'), 0) ) | int > 60 }}"
      - condition: state
        entity_id: input_boolean.backyard_south_camera_notifications
        state: "on"
    actions:
      - action: script.camera_detection_alert
        data:
          detection_type: "animal"
          camera_name: "{{ camera_name }}"
          image_path: "{{ image_path }}"
          proxy_camera: "{{ proxy_camera }}"
          snooze_timer: "{{ snooze_timer }}"
          notifications_boolean: "{{ notifications_boolean }}"
