# Nino's Bedroom - Turn off Air Purifier
# 
# Automation logic to handle turning off the
# air purifier when we don't need it
# 
automation:
  - id: "nino_bedroom_turn_off_purifier"
    alias: Nino's Bedroom Air Quality - Turn off Purifier
    mode: single
    initial_state: on
    triggers:
      # House becomes unoccupied
      - trigger: state
        entity_id: input_boolean.house_occupied
        to: "off"

      # Nino's room becomes unoccupied for 
      - trigger: state
        entity_id: input_boolean.ninos_bedroom_occupied
        to: "off"
        for:
          minutes: 30
    conditions:
      - condition: state
        entity_id: input_boolean.construction_mode
        state: "off"
    actions:
      # Turn OFF the air purifer
      - action: fan.turn_off
        target:
          entity_id: fan.ninos_bedroom_air_purifier
