# Turn on the outlets when the bathroom is occupied
# 
automation:
  - id: "main_bathroom_turn_on_outlets"
    initial_state: on
    alias: "Main Bathroom - Turn On Outlets"
    trigger:
      # Bathroom is occupied
      - platform: state
        entity_id: input_boolean.main_bathroom_occupied
        to: "on"
    action:
      - service: switch.turn_on
        entity_id:
          - switch.smart_plug_12_switch
          - switch.smart_plug_13_switch
