automation:
  - id: "fire_alarm_shut_off_hvac"
    alias: "Fire Alarm - Shut Off HVAC"
    mode: "single"
    triggers:
      # Smoke detector detects smoke
      - trigger: state
        entity_id: binary_sensor.smoke_detector
        from: "off"
        to: "on"
    actions:
      - action: script.fire_alarm_alert
        data: {}

script:
  fire_alarm_alert:
    alias: "Fire Alarm - Alert"
    mode: "single"
    icon: mdi:alert
    sequence:
      # Turn OFF the HVAC
      - action: climate.turn_off
        target:
          entity_id:
            - climate.nest_main_floor
            - climate.nest_2nd_floor

      # Trigger a critical announcement
      - action: script.critical_announcement
        data:
          media_players: all
          sound: "nuclear"
          speech_message: Alert! The smoke detector has been trigger. Get to safety immediately!

      # Flash the lights
      - action: script.alarm_flash_lights
        data: {}

      # Send a push notification
      - action: script.general_notification
        data:
          message: The smoke detector has activated, I'm turning off the HVAC. Please get to safety!
          title: Fire & Smoke Alarm
          devices: "jk"
          priority: "critical"
          tag: "home-fire-alarm"
