# Kitchen - Turn off Air Purifier
# 
# Automation logic to handle turning off the
# air purifier when we don't need it
# 
automation:
  - id: "office_turn_off_purifier"
    alias: Office Air Quality - Turn off Purifier
    mode: single
    initial_state: on
    triggers:
      # House becomes unoccupied
      - trigger: state
        entity_id: input_boolean.house_occupied
        to: "off"
    conditions:
      - condition: state
        entity_id: input_boolean.construction_mode
        state: "off"
    actions:
      # Turn OFF the air purifer
      - action: fan.turn_off
        target:
          entity_id: fan.office_air_purifier
