# Main Bedroom - Turn off Air Purifier
# 
# Automation logic to handle turning off the
# air purifier when we don't need it
# 
automation:
  - id: "main_bedroom_turn_off_purifier"
    alias: Main Bedroom Air Quality - Turn off Purifier
    mode: single
    initial_state: on
    triggers:
      # House becomes unoccupied
      - trigger: state
        entity_id: input_boolean.house_occupied
        to: "off"
      # Main Bedroom turns OFF
      - trigger: state
        entity_id: input_select.main_bedroom
        to: "Off"
      # Main Bedroom becomes unoccupied for 
      - trigger: state
        entity_id: input_boolean.main_bedroom_occupied
        to: "off"
        for:
          minutes: 30
    actions:
      # Turn OFF the air purifer
      - action: fan.turn_off
        target:
          entity_id: fan.main_bedroom_air_purifier 