automation:
  - id: "joe_announce_departure"
    alias: Joe Announce Departure
    mode: queued
    initial_state: on
    triggers:
      - trigger: state
        entity_id: input_boolean.joe_home
        to: "off"
    conditions:
      # Somebody has been home for 5 minutes
      - condition: state
        entity_id: input_boolean.house_occupied
        state: "on"
        for:
          minutes: 5
    actions:
      # Announcement script
      - action: script.person_announcement
        data:
          person: joe
          announcement_type: departure
      # # Announcement
      # - service: script.voice_announcement
      #   data:
      #     media_players: auto
      #     sound: "fox-nfl"
      #     speech_message: >-
      #       {{
      #         [
      #           "Arrivederci! Joe G has left the house.",
      #           "Pardon the interruption but Joe G has left the house!",
      #           "Attention! Joe G is no longer home."
      #         ] | random
      #       }}
