# Quiet Mode - Turn Off
#
# If nobody is in bed then turn off quiet mode
# and enable voice notifications and other automations
#
automation:
  - id: "quiet_mode_turn_off"
    initial_state: on
    alias: "Quiet Mode - Turn Off"
    triggers:
      # Everybody is Awake
      - trigger: state
        entity_id: binary_sensor.everybody_awake
        to: "on"
    conditions:
      # Quiet mode is oFF
      - condition: state
        entity_id: input_boolean.quiet_mode
        state: "on"
      # No bed is occupied
      - condition: and
        conditions:
          - condition: state
            entity_id: binary_sensor.nino_bed_occupied
            state: "off"
          - condition: state
            entity_id: binary_sensor.gianluca_bed_occupied
            state: "off"
          - condition: state
            entity_id: binary_sensor.john_bed_occupied
            state: "off"
          - condition: state
            entity_id: binary_sensor.cristina_bed_occupied
            state: "off"
    actions:
      # Toggle the input boolean
      - action: input_boolean.turn_off
        entity_id: input_boolean.quiet_mode
