# Quiet Mode - Turn On
#
# If somebody is in bed then turn quiet mode on
# to disable voice notifications and quiet down the house
#
automation:
  - id: "quiet_mode_turn_on"
    initial_state: on
    alias: "Quiet Mode - Turn On"
    triggers:
      # Somebody is in bed
      - trigger: state
        entity_id: binary_sensor.somebody_in_bed
        to: "on"
    conditions:
      # Quiet mode is oFF
      - condition: state
        entity_id: input_boolean.quiet_mode
        state: "off"
    actions:
      # Toggle the input boolean
      - action: input_boolean.turn_on
        entity_id: input_boolean.quiet_mode

      # Announce to the house
      - action: script.voice_announcement
        data:
          media_players: auto
          sound: harp-flourish
          speech_message: >-
            {% set who = "" %}
            {% if states.input_boolean.gianluca_in_bed.state == "on" %}
              {% set who = "Gianluca" %}
            {% elif states.input_boolean.nino_in_bed.state == "on" %}
              {% set who = "Nino" %}
            {% elif states.input_boolean.john_is_in_bed.state == "on" %}
              {% set who = "John" %}
            {% elif states.input_boolean.cristina_in_bed.state == "on" %}
              {% set who = "Cristina" %}
            {% endif %}

            {{
              [
                "Shhh..." ~ who ~ " is going to sleep.",
                "Quiet time, " ~ who ~ " is going to sleep!",
                "Pardon the interruption but " ~ who ~ " is going to sleep, please be quiet!",
                "Attention! Quiet mode has been enabled for " ~ who ~ "'s nap."
              ] | random
            }}
