# Bedtime Mode On
#
# If everybody is in bed then we'll turn
# bedtime mode on to shut down unused areas
#
automation:
  - id: "bedtime_mode_on"
    initial_state: on
    alias: "Bedtime Mode - On"
    triggers:
      # Everybody in bed turned on
      - trigger: state
        entity_id: binary_sensor.everybody_in_bed
        to: "on"
    conditions:
      # House is occupied
      - condition: state
        entity_id: input_boolean.house_occupied
        state: "on"
    action:
      - action: input_boolean.turn_on
        entity_id: input_boolean.bedtime
