# Automation to detect and initiate away for Nonna
#
#
automation:
  - id: "nonna_is_away"
    alias: "Nonna is Away"
    initial_state: on
    triggers:
      # Nonna not home
      - trigger: state
        entity_id: person.mary_falbo
        to: "not_home"
      # Nonna bayesian sensor is OFF
      - trigger: state
        entity_id: binary_sensor.nonna_presence
        to: "off"
      # Handle restarts and reloads of HA
      - trigger: event
        event_type: automation_reloaded
      - trigger: homeassistant
        event: start
    conditions:
      # Didn't just leave
      - condition: not
        conditions:
          - condition: state
            entity_id: input_select.nonna_status
            state: "Just Left"
      - or:
          # Bayesian sensor is OFF
          - condition: state
            entity_id: binary_sensor.nonna_presence
            state: "off"
          # OR Person is NOT HOME
          - condition: state
            entity_id: person.mary_falbo
            state: "off"
    actions:
      - action: input_boolean.turn_off
        entity_id: input_boolean.nonna_home
