# Driveway Front Camera Detects a Vehicle
#
automation:
  - id: "driveway_front_camera_detections_vehicle"
    alias: "Driveway Front Camera Detections - Vehicle"
    mode: "single"
    triggers:
      - trigger: state
        entity_id: binary_sensor.driveway_front_camera_vehicle_detected
        to: "on"
        variables:
          camera_name: "Driveway Front Camera"
          nvr_id: "{{ config_entry_id(trigger.entity_id) }}"
          event_id: "{{ trigger.to_state.attributes.event_id }}"
          image_path: /api/unifiprotect/thumbnail/{{ nvr_id }}/{{ event_id }}
          proxy_camera: camera.camera_proxy_camera_driveway_front_camera_high
          snooze_timer: timer.driveway_front_camera_notifications_snooze_timer
          notifications_boolean: input_boolean.driveway_front_camera_notifications
    conditions:
      - condition: template
        value_template: "{{ ( now().timestamp() - as_timestamp(state_attr('automation.driveway_front_camera_detections_vehicle','last_triggered'), 0) ) | int > 60 }}"
      - condition: state
        entity_id: input_boolean.driveway_front_camera_notifications
        state: "on"
    actions:
      - action: script.camera_detection_alert
        data:
          detection_type: "vehicle"
          camera_name: "{{ camera_name }}"
          image_path: "{{ image_path }}"
          proxy_camera: "{{ proxy_camera }}"
          snooze_timer: "{{ snooze_timer }}"
          notifications_boolean: "{{ notifications_boolean }}"
