automation:
  - id: "gianlucas_room_occupied"
    initial_state: on
    alias: "Gianluca's room occupied"
    triggers:
      # Gianluca's door is closed
      - trigger: state
        entity_id: binary_sensor.gianlucas_door_sensor_status
        to: "off"
      # Lights turned on
      - trigger: state
        entity_id: light.gianluca_ceiling_lights
        to: "on"
      # Bed is occupied
      - trigger: state
        entity_id: binary_sensor.gianluca_bed_occupied
        to: "on"
    conditions:
      # Not currently occupied
      - condition: state
        entity_id: input_boolean.gianlucas_room_occupied
        state: "off"
      - condition: or
        conditions:
          # Gianluca's door is closed
          - condition: state
            entity_id: binary_sensor.gianlucas_door_sensor_status
            state: "off"
          # Gianluca's lights are ON
          - condition: state
            entity_id: light.gianluca_ceiling_lights
            state: "on"
          # OR his bed is occupied
          - condition: state
            entity_id: binary_sensor.gianluca_bed_occupied
            state: "on"
    actions:
      - action: input_boolean.turn_on
        entity_id: input_boolean.gianlucas_room_occupied
