# Gianluca's Bedroom Mode Off
#
automation:
  - id: "gianlucas_bedroom_mode_off"
    initial_state: on
    alias: "Gianluca's Bedroom - Mode Off"
    triggers:
      # House becomes unoccupied
      - trigger: state
        entity_id: input_boolean.house_occupied
        to: "off"
      # House is turned to Away
      - trigger: state
        entity_id: input_select.house
        to: "Away"
      # Hassio restart/relaod
      - trigger: homeassistant
        event: start
      - trigger: event
        event_type: automation_reloaded
    conditions:
      # Not currently Off
      - condition: template
        value_template: "{{ not is_state('input_select.gianlucas_bedroom','Off') }}"
      - condition: or
        conditions:
          # House is not occupied
          - condition: state
            entity_id: input_boolean.house_occupied
            state: "off"
          # OR House is in Away mode
          - condition: state
            entity_id: input_select.house
            state: "Away"
    actions:
      - action: input_select.select_option
        data:
          entity_id: input_select.gianlucas_bedroom
          option: "Off"
