# Gianluca's Bedroom Air Quality Detections
#
# If PM2.5, CO2, or TVOCs breach thresholds
# then turn on the air purifier.
#
automation:
  - id: "gianluca_bedroom_air_quality_detections"
    alias: Gianluca's Bedroom Air Quality Sensor Detections
    mode: single
    initial_state: on
    triggers:
      # Triggered by any change to the air quality state
      - trigger: state
        entity_id: sensor.gianluca_bedroom_air_quality

      # Trigger if gianluca's bedroom is set to bedtime
      - trigger: state
        entity_id: input_select.gianlucas_bedroom
        to: "Bedtime"

      # Trigger if gianluca's occupancy changes
      - trigger: state
        entity_id: input_boolean.gianlucas_room_occupied
    conditions:
      - or:
          # House is occupied
          - condition: state
            entity_id: input_boolean.house_occupied
            state: "on"
          # Or we're almost home
          - condition: state
            entity_id: input_boolean.almost_home
            state: "on"
    variables:
      purifier: fan.gianlucas_bedroom_air_purifier
      aqi_state: "{{ trigger.to_state.state }}"
      room_state: "{{ states.input_select.gianlucas_bedroom.state }}"
    actions:
      # Call the air quality set purifier mode script
      # and let it handle the logic for speed and mode
      - action: script.air_quality_set_air_purifier_mode
        data:
          purifier: "{{ purifier }}"
          aqi_state: "{{ aqi_state }}"
          room_state: "{{ room_state }}"
