automation:
  - id: "main_bedroom_john_night_light_off"
    initial_state: on
    alias: "Main bedroom night light for John - Turn Off"
    triggers:
      # John's in bed
      - trigger: state
        entity_id: input_boolean.john_is_in_bed
        to: "on"
        for:
          minutes: 10
      # Bedtime enabled for 5 minutes
      - trigger: state
        entity_id: input_boolean.bedtime
        to: "on"
        for:
          minutes: 5
      # Turn off if it's been on for 10 mins
      - trigger: state
        entity_id: light.hue_ambiance_lamp_1
        to: "on"
        for:
          minutes: 10
    conditions:
      # Light automations are enabled
      - condition: state
        entity_id: input_boolean.lighting_automations
        state: "on"
      # Bedroom is in Auto or Bedtime mode
      - condition: or
        conditions:
          # Bedroom is Auto
          - condition: state
            entity_id: input_select.main_bedroom
            state: "Auto"
          # Bedroom is Bedtime
          - condition: state
            entity_id: input_select.main_bedroom
            state: "Bedtime"
      # Bedroom is occupied
      - condition: state
        entity_id: input_boolean.main_bedroom_occupied
        state: "on"
      # John is in bed
      - condition: state
        entity_id: input_boolean.john_is_in_bed
        state: "on"
        for:
          minutes: 10
    actions:
      - action: light.turn_off
        entity_id:
          - light.hue_ambiance_lamp_1
          - light.hue_ambiance_lamp_1_2
