# Foyer Lights Sleep Mode On
#
# The Foyer has a few Hue bulbs and uses adaptive
# lighting, but we need to make sure that sleep mode
# is on in the evenings after the sun is down
#
automation:
  - id: "foyer_lights_sleep_mode_on"
    initial_state: off
    alias: "Foyer Lights Sleep Mode On"
    triggers:
      # House goes into bedtime mode:
      - trigger: state
        entity_id: input_boolean.bedtime
        to: "on"
      # At 11pm
      - trigger: time
        at: "23:00:00"
      # Somebody is in bed
      - trigger: state
        entity_id: binary_sensor.somebody_in_bed
        to: "on"
        for:
          minutes: 3
    condition:
      # Lighting automations must be enabled
      - condition: state
        entity_id: input_boolean.lighting_automations
        state: "on"
      # Sun is set
      - condition: sun
        after: sunset
      # It's dark outside
      - condition: state
        entity_id: input_boolean.dark_outside
        state: "on"
      # After 7pm
      - condition: time
        after: "19:00:00"
    action:
      - service: switch.turn_on
        entity_id: switch.adaptive_lighting_sleep_mode_foyer
