automation:
  - id: "garage_door_3_open_upon_arrival"
    alias: "Garage Door 3 - Open Upon Arrival"
    initial_state: off
    triggers:
      # People just got home
      - trigger: state
        entity_id:
          # - input_select.cristina_status_dropdown
          - input_select.john_status
        to: "Just Arrived"
      # BMW just arrived
      - trigger: state
        entity_id: input_boolean.bmw_home
        to: "on"
    conditions:
      # Somebody just arrived
      - condition: or
        conditions:
          # Cristina just arrived
          - condition: state
            entity_id: input_select.cristina_status_dropdown
            state: "Just Arrived"
          # OR John just arrived
          - condition: state
            entity_id: input_select.john_status
            state: "Just Arrived"
      - condition: and
        conditions:
          # BMW is home
          - condition: state
            entity_id: input_boolean.bmw_home
            state: "on"
          # AND BMW boolean just recently updated
          - condition: template
            value_template: "{{ (as_timestamp(now()) - as_timestamp(states.input_boolean.bmw_home.last_updated)) | int < 120 }}"
      # Garage 3 is close
      - condition: state
        entity_id: cover.garage_door_3
        state: "closed"

    actions:
      # Close the garage doors
      - action: cover.open_cover
        entity_id: cover.garage_door_3

      # Notification for logging
      - action: script.general_notification
        data:
          title: "Garage Door 3"
          message: Garage door three is opening upon somebody's arrival
          devices: "jk"
          priority: "active"
          tag: "garage-door-3-automation"
