# Jr. Suite - Turn off Air Purifier
# 
# Automation logic to handle turning off the
# air purifier when we don't need it
# 
automation:
  - id: "jr_suite_turn_off_purifier"
    alias: Jr. Suite Air Quality - Turn off Purifier
    mode: single
    initial_state: on
    triggers:
      # House becomes unoccupied
      - trigger: state
        entity_id: input_boolean.house_occupied
        to: "off"
      # Jr. Suite turns OFF
      - trigger: state
        entity_id: input_select.jr_suite
        to: "Off"
    conditions:
      - condition: state
        entity_id: input_boolean.construction_mode
        state: "off"
    actions:
      # Turn OFF the air purifer
      - action: fan.turn_off
        target:
          entity_id: fan.jr_suite_air_purifier