# Automation to detect and initiate away for Katia
#
#
automation:
  - id: "katia_is_away"
    alias: "Katia Is Away"
    initial_state: on
    triggers:
      # katia not home
      - trigger: state
        entity_id: person.katia
        to: "not_home"
      # Bayesian is OFF
      - trigger: state
        entity_id: binary_sensor.katia_presence
        to: "off"
      # Handle restarts and reloads of HA
      - trigger: event
        event_type: automation_reloaded
      - trigger: homeassistant
        event: start
    conditions:
      # Didn't just leave
      - condition: not
        conditions:
          - condition: state
            entity_id: input_select.katia_status
            state: "Just Left"
      - or:
          # Person is not home
          - condition: state
            entity_id: person.katia
            state: "not_home"
          # OR bayesian is OFF
          - condition: state
            entity_id: binary_sensor.katia_presence
            state: "off"
    actions:
      - action: input_boolean.turn_off
        entity_id: input_boolean.katia_home
