# Automation to detect and initiate home for Katia
#
#
automation:
  - id: "katia_is_home"
    initial_state: on
    alias: "Katia is Home"
    triggers:
      # Person marked HOME
      - trigger: state
        entity_id: person.katia
        to: "home"
      # Bayesian sensor ON
      - trigger: state
        entity_id: binary_sensor.katia_presence
        to: "on"
      # Hassio restart/reload
      - trigger: event
        event_type: automation_reloaded
      - trigger: homeassistant
        event: start
    conditions:
      # katia_home boolean is OFF
      - condition: state
        entity_id: input_boolean.katia_home
        state: "off"
      - or:
          # Person marked as HOME
          - condition: state
            entity_id: person.katia
            state: "home"
          # OR bayesian sensor is ON
          - condition: state
            entity_id: binary_sensor.katia_presence
            state: "on"
    actions:
      - action: input_boolean.turn_on
        entity_id: input_boolean.katia_home
