automation:
  - id: "alarm_disarm_when_house_becomes_occupied"
    alias: "Alarm - Disarm When House Becomes Occupied"
    mode: "single"
    triggers:
      # House becomes occupied
      - trigger: state
        entity_id: input_boolean.house_occupied
        from: "off"
        to: "on"
    conditions:
      # Alarm is currently armed
      - condition: state
        entity_id: alarm_control_panel.panel
        state:
          - "armed_home"
          - "armed_away"
      # House is occupied
      - condition: state
        entity_id: input_boolean.house_occupied
        state: "on"
    actions:
      # Disarm the alarm
      - action: alarm_control_panel.alarm_disarm
        entity_id: alarm_control_panel.panel

      - action: script.general_notification
        data:
          message: Home is now disarmed upon the arrival of somebody.
          title: Home Security System
          devices: "jk"
          priority: "active"
          tag: "home-security"
