# John DnD Off
# 
# If I'm off a call, turn off the DnD boolean
automation:
  - id: "john_dnd_off"
    initial_state: on
    alias: "John DnD Off"
    mode: queued
    triggers:
      # Work call boolean is OFF
      - trigger: state
        entity_id: input_boolean.john_work_call
        to: "off"
      # Work call boolean is OFF
      - trigger: state
        entity_id: input_boolean.john_work_call
        to: "off"
        for:
          seconds: 60
      # Webcam turned OFF for 30 seconds
      - trigger: state
        entity_id: binary_sensor.john_laptop_camera_active
        to: "off"
        for:
          seconds: 30
      # Computer audio OFF for 30 seconds
      - trigger: state
        entity_id: binary_sensor.john_laptop_audio_active
        to: "off"
        for:
          seconds: 30
    conditions:
      # Camera is off
      - condition: state
        entity_id: binary_sensor.john_laptop_camera_active
        state: "off"
      # Computer audio is inactive
      - condition: state
        entity_id: binary_sensor.john_laptop_audio_active
        state: "off"
      # DnD is currently ON
      - condition: state
        entity_id: input_boolean.john_dnd
        state: "on"
    actions:
      # Turn OFF the dnd boolean
      - action: input_boolean.turn_off
        entity_id: input_boolean.john_dnd
