# John DnD On
# 
# If I'm on a call, turn ON the DnD boolean
automation:
  - id: "john_dnd_on"
    initial_state: on
    alias: "John DnD On"
    mode: queued
    triggers:
      # Webcam turned on
      - trigger: state
        entity_id: binary_sensor.john_laptop_camera_active
        to: "on"
        for:
          seconds: 3
      # Computer audio turned ON for 5 seconds
      - trigger: state
        entity_id: binary_sensor.john_laptop_audio_active
        to: "on"
        for:
          seconds: 5
      # On a work call
      - trigger: state
        entity_id: input_boolean.john_work_call
        to: "on"
        for:
          seconds: 5
    conditions:
      - condition: or
        conditions:
          # Camera is ON
          - condition: state
            entity_id: binary_sensor.john_laptop_camera_active
            state: "on"
          # Computer audio is ON
          - condition: state
            entity_id: binary_sensor.john_laptop_audio_active
            state: "on"
      # Not already active
      - condition: state
        entity_id: input_boolean.john_dnd
        state: "off"
    actions:
      # Turn ON the dnd boolean
      - action: input_boolean.turn_on
        entity_id: input_boolean.john_dnd
      # Notification for logging
      - action: script.general_notification
        data:
          message: "John's DnD mode has been turned on"
          title: "John DnD On!"
          devices: "jk"
          priority: "passive"
          tag: "john-dnd"
