# Main Bedroom Not Occupied
#
automation:
  - id: "main_bedroom_not_occupied"
    initial_state: on
    alias: "Main bedroom not occupied"
    triggers:
      # Anybody detected via BLE
      - trigger: state
        entity_id: binary_sensor.main_bedroom_ble_occupancy
        to: "off"
        for:
          minutes: 2
      # Bedtime is disabled
      - trigger: state
        entity_id: input_boolean.bedtime
        to: "off"
      # No motion detected for 5 minutes
      - trigger: state
        entity_id: binary_sensor.main_bedroom_motion_sensor
        to: "off"
        for:
          minutes: 5
      # No aqara occupancy
      - trigger: state
        entity_id: binary_sensor.main_bedroom_motion_sensor_occupancy
        to: "off"
      # No aqara occupancy for 5 minutes
      - trigger: state
        entity_id: binary_sensor.main_bedroom_motion_sensor_occupancy
        to: "off"
        for:
          minutes: 5
      # Main bathroom becomes unoccupied
      # When somebody showers, the bathroom might take a little
      # while to register as unoccupied.
      - trigger: state
        entity_id: input_boolean.main_bathroom_occupied
        to: "off"
    conditions:
      # The bedroom is occupied
      - condition: state
        entity_id: input_boolean.main_bedroom_occupied
        state: "on"
      # Anybody detected via BLE
      - condition: state
        entity_id: binary_sensor.main_bedroom_ble_occupancy
        state: "off"
      # Main bathroom is not occupied
      - condition: state
        entity_id: input_boolean.main_bathroom_occupied
        state: "off"
      # It's not bedtime
      - condition: state
        entity_id: input_boolean.bedtime
        state: "off"
      # No occupancy for 5 minutes
      - condition: state
        entity_id: binary_sensor.main_bedroom_motion_sensor_occupancy
        state: "off"
      # Nobody is in bed
      - and:
          - condition: state
            entity_id: input_boolean.john_is_in_bed
            state: "off"
          - condition: state
            entity_id: input_boolean.cristina_in_bed
            state: "off"
      # Auto mode between 5-midnight
      # OR bedtime mode and between 6am-9pm
      - condition: or
        conditions:
          # Auto mode between 5am - 11:59
          - condition: and
            conditions:
              # Not in bedtime mode
              - condition: template
                value_template: "{{ not is_state('input_select.main_bedroom','Bedtime') }}"
              # Between 5 - 12am
              - condition: time
                after: "05:00:00"
                before: "23:59:59"
          # OR it's bedtime mode and betwen 4-10
          - condition: and
            conditions:
              # Not in bedtime mode
              - condition: state
                entity_id: input_select.main_bedroom
                state: "Bedtime"
              # It's between 6am - 9pm
              - condition: time
                after: "06:00:00"
                before: "21:00:00"
    action:
      - action: input_boolean.turn_off
        entity_id: input_boolean.main_bedroom_occupied

      # Wati 2 seconds to activate lighting automations
      - alias: "Wait 2 seconds"
        delay: 02

      - action: input_boolean.turn_on
        entity_id: input_boolean.main_bedroom_lighting_automations
