# Nonno Status
#
# This automation manages an input_select that manages
# the state of the person, e.g. home, just left, just
# arrived, or away
#

input_select:
  nonno_status:
    name: Nonno
    options:
      - Home
      - Just Arrived
      - Just Left
      - Away
    initial: Away

automation:
  #
  # Nonno Presence Just Arrived
  # Mark him as just arrived once detected home
  #
  - id: "nonno_presence_just_arrived"
    alias: Nonno Presence - Just Arrived
    mode: single
    initial_state: on
    triggers:
      - trigger: state
        entity_id: input_boolean.nonno_home
        to: "on"
    actions:
      - action: input_select.select_option
        data:
          entity_id: input_select.nonno_status
          option: "{{ 'Home' if states.input_select.nonno_status.state else 'Just Arrived' }}"

  #
  # Nonno Presence Home
  # Mark him as home after having arrived for 5 mins
  #
  - id: "nonno_presence_home"
    alias: Nonno Presence - Home
    mode: single
    initial_state: on
    triggers:
      - trigger: state
        entity_id: input_select.nonno_status
        to: "Just Arrived"
        for:
          minutes: 5
      - trigger: state
        entity_id: input_select.nonno_status
        from: "Just Left"
        to: "Just Arrived"
    actions:
      - action: input_select.select_option
        data:
          entity_id: input_select.nonno_status
          option: Home

  #
  # Nonno Presence Just Left
  # Mark him as Just Left upon departure
  #
  - id: "nonno_presence_just_left"
    alias: Nonno Presence - Just Left
    mode: single
    initial_state: on
    triggers:
      - trigger: state
        entity_id: input_boolean.nonno_home
        to: "off"
    actions:
      - action: input_select.select_option
        data:
          entity_id: input_select.nonno_status
          option: Just Left

  # Mark person as Away
  #
  # If a person has been in the Just Left status for
  # more than 5 minutes, let's consider them Away.
  - id: "nonno_presence_away"
    alias: Nonno Presence - Away
    mode: single
    initial_state: on
    triggers:
      - trigger: state
        entity_id: input_select.nonno_status
        to: "Just Left"
        for:
          minutes: 5
    actions:
      - action: input_select.select_option
        data:
          entity_id: input_select.nonno_status
          option: Away
