# Outdoor Air Quality Alerts
#
# This automation is responsible for notifying us if
# there are air quality issues in our city.
#

#
# Air Quality State
# This simply stores the current state of the
# local air quality. Changes to the value of this
# input_select will trigger the automations
#
input_select:
  air_quality_state:
    name: Air Quality State
    options:
      - Good
      - Moderate
      - Slightly Unhealthy
      - Unhealthy
      - Very Unhealthy
      - Hazardous

automation:
  #
  # AQI becomes good
  # If the input_select.air_quality_state goes from
  # very unhealthy to good, then turn off the air purifiers
  #
  - id: "air_quality_alert_good"
    alias: "Air Quality - Alert for Good Conditions"
    initial_state: on
    trigger:
      - trigger: state
        entity_id: input_select.air_quality_state
        to: "Good"
    actions:
      - action: script.air_quality_alert_set_air_purifier_auto

  #
  # AQI becomes unhealthy
  # If the input_select.air_quality_state goes from
  # good, moderate or slightly unhealthy to unhealthy,
  # then broadcast an announcement in the house
  #
  - id: "air_quality_alert_unhealthy"
    alias: "Air Quality - Alert for Unhealthy Conditions"
    initial_state: on
    trigger:
      - trigger: state
        entity_id: input_select.air_quality_state
        from:
          - "Good"
          - "Moderate"
          - "Slightly Unhealthy"
        to: "Unhealthy"
        for:
          minutes: 5
    conditions:
      # Automation hasn't run in 2 hours
      - condition: template
        value_template: "{{ ( now().timestamp() - as_timestamp(state_attr('automation.air_quality_alert_unhealthy','last_triggered'), 0) ) | int > 7200 }}"
    actions:
      #
      # Announce the air quality alert
      #
      - action: script.voice_announcement
        data:
          media_players: auto
          sound: one-chime
          priority: high
          expires_in: 60
          speech_message: Hey Fam, the air quality is looking unhealthy, please keep windows closed and make sure to take precautions.
      #
      # Turn on the air purifiers to 25%
      #
      - action: script.air_quality_alert_turn_on_air_purifiers
        data:
          speed: 25

  #
  # AQI becomes very unhealthy
  # If the input_select.air_quality_state becomes
  # very unhealthy then trigger a broadcast AND
  # turn on the air purifiers to 50%
  #
  - id: "air_quality_alert_very_unhealthy"
    alias: "Air Quality - Alert for Very Unhealthy Conditions"
    initial_state: on
    trigger:
      - trigger: state
        entity_id: input_select.air_quality_state
        from:
          - "Good"
          - "Moderate"
          - "Slightly Unhealthy"
          - "Unhealthy"
        to: "Very Unhealthy"
        for:
          minutes: 5
    conditions:
      # Automation hasn't run in 2 hours
      - condition: template
        value_template: "{{ ( now().timestamp() - as_timestamp(state_attr('automation.air_quality_alert_very_unhealthy','last_triggered'), 0) ) | int > 7200 }}"
    actions:
      #
      # Announce the air quality alert
      #
      - action: script.voice_announcement
        data:
          media_players: auto
          sound: one-chime
          priority: high
          expires_in: 60
          speech_message: Hey Fam, the air quality is looking very unhealthy, please keep windows closed and make sure to take precautions.
      #
      # Turn on the air purifiers to 50%
      #
      - action: script.air_quality_alert_turn_on_air_purifiers
        data:
          speed: 50


  #
  #  AQI becomes hazardous
  # If the input_select.air_quality_state becomes
  # hazardous then trigger a nuclear broadcast AND
  # turn on the air purifiers to 100%
  #
  - id: "air_quality_alert_hazardous"
    alias: "Air Quality - Alert for Very Unhealthy Conditions"
    initial_state: on
    triggers:
      - trigger: state
        entity_id: input_select.air_quality_state
        to: "Hazardous"
        for:
          minutes: 2
    conditions:
      # Automation hasn't run in 2 hours
      - condition: template
        value_template: "{{ ( now().timestamp() - as_timestamp(state_attr('automation.air_quality_alert_hazardous','last_triggered'), 0) ) | int > 7200 }}"
    actions:
      #
      # Announce the air quality alert
      #
      - action: script.voice_announcement
        data:
          media_players: auto
          sound: nuclear
          priority: critical
          speech_message: Attention! The air quality is hazardous today. Please stay indoors as much as possible.
      #
      # Turn on the air purifiers to 100%
      #
      - action: script.air_quality_alert_turn_on_air_purifiers
        data:
          speed: 100
  #
  # Set the Air Quality State input select
  # This automation listens to the local air quality index'
  # and updates the input_select above based on the air
  # quality score
  #
  - id: "update_air_quality_state"
    alias: Update Air Quality State
    mode: "single"
    triggers:
      - trigger: state
        entity_id: sensor.desplns_illinois_usa_air_quality_index
      # Hassio reloads/starts
      - trigger: event
        event_type: automation_reloaded
      - trigger: homeassistant
        event: start
    action:
      - action: input_select.select_option
        data:
          entity_id: input_select.air_quality_state
          option: >
            {% set aqi = states.sensor.desplns_illinois_usa_air_quality_index.state | int %}
            {% if aqi <= 50 %}
              Good
            {% elif aqi <= 100 %}
              Moderate
            {% elif aqi <= 150 %}
              Slightly Unhealthy
            {% elif aqi <= 200 %}
              Unhealthy
            {% elif aqi <= 300 %}
              Very Unhealthy
            {% else %}
              Hazardous
            {% endif %}



script:
  #
  # Turn on the air purifiers and set the speed
  #
  air_quality_alert_turn_on_air_purifiers:
    alias: "Air Quality Alert - Turn on Air Purifiers"
    mode: queued
    fields:
      speed:
        description: "Speed to set the air purifiers to"
        example: "25"
        default: "25"
        selector:
          select:
            options:
              - "25"
              - "50"
              - "75"
              - "100"
    # 
    # Purifier to set
    sequence:
      - action: fan.turn_on
        data:
          entity_id: fan.air_purifiers
      - action: fan.set_preset_mode
        data:
          entity_id: fan.air_purifiers
          preset_mode: Manual
      - action: fan.set_percentage
        data:
          entity_id: fan.air_purifiers
          percentage: "{{ speed }}"

  # 
  # Set the air purifier to auto
  #
  air_quality_alert_set_air_purifier_auto:
    alias: "Air Quality Alert - Set Air Purifier to Auto"
    mode: queued
    sequence:
      - action: fan.set_preset_mode
        data:
          entity_id: fan.air_purifiers
          preset_mode: Auto