id: "bedtime"
initial_state: "off"
alias: "Bedtime"
triggers:
  - trigger: state
    entity_id:
      - input_boolean.john_is_in_bed
      - input_boolean.cristina_in_bed
    to: "on"
    id: "person_in_bed"
  # At 9pm
  - trigger: time
    at: "21:00:00"
    id: "bedtime_time"
  # Everybody in bed turned on
  - trigger: state
    entity_id: binary_sensor.everybody_in_bed
    to: "on"
conditions:
  # After 9pm and before 5am
  - condition: time
    after: "21:00:00"
    before: "05:00:00"
  # If the trigger is time, then make sure that the
  # house is empty
  - and:
      # Triggered by time
      - condition: trigger
        id: "bedtime_time"
      # house is empty
      - condition: state
        entity_id: input_boolean.house_occupied
        state: "off"
  - condition: state
    entity_id: binary_sen
  # - condition: and
  #   conditions:
  #     # John is in bed OR out of town
  #     - condition: or
  #       conditions:
  #         - condition: state
  #           entity_id: input_boolean.john_is_in_bed
  #           state: "on"
  #         # If I'm not home the house should
  #         # skip my bed detection
  #         - condition: state
  #           entity_id: input_boolean.john_home
  #           state: "off"
  #     # Cristina is in bed OR out of town
  #     - condition: or
  #       conditions:
  #         - condition: state
  #           entity_id: input_boolean.cristina_in_bed
  #           state: "on"
  #         # If Cristina's NOT HOME then the house should
  #         # skip my bed detection
  #         - condition: state
  #           entity_id: input_boolean.cristina_home
  #           state: "off"
action:
  - action: input_boolean.turn_on
    entity_id: input_boolean.bedtime
