sensor:
  - platform: min_max
    name: Second Floor Humidity
    type: mean
    round_digits: 1
    entity_ids:
      - sensor.main_bedroom_awair_humidity
      - sensor.gianluca_bedroom_awair_humidityy
      - sensor.nino_bedroom_awair_humidity
      - sensor.guest_bedroom_humidity
