# Main Bathroom Mode Bedtime
#
automation:
  - id: "main_bathroom_mode_bedtime"
    initial_state: on
    alias: "Main Bathroom mode bedtime"
    triggers:
      # # Bedtime is enabled
      - trigger: state
        entity_id: input_boolean.bedtime
        to: "on"
      # Bedtime hours active
      - trigger: state
        entity_id: binary_sensor.bedtime
        to: "on"
      # When the main bedroom goes to Bedtime mode
      - trigger: state
        entity_id: input_select.main_bedroom
        to: "Bedtime"
    conditions:
      # Bathroom is not already Bedtime
      - condition: template
        value_template: "{{ not is_state('input_select.main_bathroom','Bedtime') }}"
      # Bedtime mode is enabled or bedroom is in bedtime mode
      - condition: or
        conditions:
          # Bedtime is enabled
          - condition: state
            entity_id: input_boolean.bedtime
            state: "on"
          # Bedroom is in bedtime mode
          - condition: state
            entity_id: input_select.main_bedroom
            state: "Bedtime"
    action:
      - action: input_select.select_option
        data:
          entity_id: input_select.main_bathroom
          option: "Bedtime"

      - choose:
          # Bathroom is currently occupied
          # Wait until the bathroom is no longer occupied
          # before we actually turn on bedtime mode automations
          - conditions:
              - condition: state
                entity_id: input_boolean.main_bathroom_occupied
                state: "on"
            sequence:
              - wait_for_trigger:
                  - trigger: state
                    entity_id: input_boolean.main_bathroom_occupied
                    to: "off"
                timeout:
                  minutes: 10
                continue_on_timeout: true
              - action: script.turn_on
                entity_id: script.main_bathroom_activate_bedtime_lighting_mode
        #
        # If bathroom is NOT occupied then just
        # run the script to activate bedtime lighting mode
        default:
          - action: script.turn_on
            entity_id: script.main_bathroom_activate_bedtime_lighting_mode

#
#
# Script: Activate Bedtime Lighting Mode
#
script:
  main_bathroom_activate_bedtime_lighting_mode:
    alias: Main Bedroom - Activate Bedtime Lighting Mode
    mode: restart
    sequence:
      # Turn on the bedtime motion automation
      - action: automation.turn_on
        entity_id: automation.main_bathroom_bedtime_motion_on

      # Turn off the regular motion automation
      - action: automation.turn_off
        entity_id: automation.main_bathroom_lights_motion_on

      # Delay 1 min
      - delay: "00:01:00"

      # Turn ON sleep mode
      - action: switch.turn_on
        entity_id:
          - switch.adaptive_lighting_sleep_mode_main_bathroom
          - switch.adaptive_lighting_sleep_mode_main_bathroom_toilet
