# Automation to detect and initiate home for Alex
#
# This automation will detect if Alex's home based on
# a bunch of triggers and conditions and then run a
# script to handle home actions.
#
automation:
  - id: "alex_is_home"
    initial_state: on
    alias: "Alex Presence - Home"
    triggers:
      # Alex detected home
      - trigger: state
        entity_id: person.alex
        to: "home"
      # iPhone detect tracker is detected home
      - trigger: state
        entity_id: device_tracker.alex_iphone_detect
        to: "home"
      - trigger: event
        event_type: automation_reloaded
      - trigger: homeassistant
        event: start
    conditions:
      - condition: state
        entity_id: person.alex
        state: "home"
    actions:
      - action: input_boolean.turn_on
        entity_id: input_boolean.alex_home
