# Gianluca School Day Off
#
# This just resets the school day boolean each night
#
automation:
  - id: "gianluca_school_day_off"
    alias: "Gianluca School Day Off"
    mode: "single"
    triggers:
      # Just before midnight
      - trigger: time
        at: "23:59:00"
      # If the school day binary sensor turns OFF
      - trigger: state
        entity_id: binary_sensor.gianluca_is_today_school_day
        to: "off"
    conditions:
      # Input boolean is currently ON
      - condition: state
        entity_id: input_boolean.gianluca_school_day
        state: "on"
    actions:
      # Turn OFF the boolean
      - action: input_boolean.turn_off
        entity_id: input_boolean.gianluca_school_day

      # Turn OFF the school reminder automation
      - action: automation.turn_off
        entity_id:
          - automation.gianluca_school_day_reminder
          - automation.gianluca_school_departure_reminder
          - automation.gianluca_school_pickup_reminder
