sensor:
  - platform: min_max
    name: Main Floor Temperature
    type: mean
    round_digits: 1
    entity_ids:
      - sensor.kitchen_awair_temperature
      - sensor.office_awair_temperature
      - sensor.playroom_awair_temperature
      - sensor.jr_suite_awair_temperature
