sensor:
  - platform: min_max
    name: Main Floor Humidity
    type: mean
    round_digits: 1
    entity_ids:
      - sensor.kitchen_awair_humidity
      - sensor.office_awair_humidity
      - sensor.playroom_awair_humidity
      - sensor.jr_suite_awair_humidity
