automation:
  - id: gianluca_bed_just_got_up
    alias: "Gianluca Bed - Just Got Up"
    mode: single
    triggers:
      # Nion's bed is NOT occupied
      - trigger: state
        entity_id: binary_sensor.gianluca_bed_occupied
        to: "off"
    action:
      - action: input_select.select_option
        data:
          entity_id: input_select.gianluca_sleep_state
          option: "Just Got Up"
