binary_sensor:
  - platform: bayesian
    prior: 0.58
    name: "Nonna Presence"
    probability_threshold: 0.97
    observations:
      # Router Detection
      #
      # Detected home
      - entity_id: "device_tracker.nonna_iphone_2"
        prob_given_true: 0.85
        prob_given_false: 0.25
        platform: "state"
        to_state: "home"

      # NMAP Device
      #
      # Detected home
      - entity_id: "device_tracker.nonna_ping_tracker"
        prob_given_true: 0.57
        prob_given_false: 0.15
        platform: "state"
        to_state: "home"

      # iPhone Detect
      #
      # Detected home
      - platform: "state"
        entity_id: "device_tracker.mary_iphone_detect"
        prob_given_true: 0.86
        prob_given_false: 0.0625
        to_state: "home"
